import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1731295630730 implements MigrationInterface {
    name = ' $npmConfigName1731295630730'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP FOREIGN KEY \`FK_765ababa7eff37efc56ec24ac9f\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_065338fbfc15984038082f46bd1\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_5c7e0f84a46dc141ed67180cef2\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP FOREIGN KEY \`FK_19ac373d1ef1e68e87e5a3633db\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP FOREIGN KEY \`FK_8e71fba12a609e08cf311fde6d9\``);
        await queryRunner.query(`ALTER TABLE \`lists\` DROP FOREIGN KEY \`FK_6077f5aded72378587df070fbfd\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP FOREIGN KEY \`FK_8b9db493288097ceee34689fc34\``);
        await queryRunner.query(`CREATE TABLE \`board_members\` (\`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP COLUMN \`projectsId\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP COLUMN \`usersId\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP COLUMN \`cardsId\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP COLUMN \`cardMembersId\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP COLUMN \`listId\``);
        await queryRunner.query(`ALTER TABLE \`lists\` DROP COLUMN \`boardsId\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP COLUMN \`projectsId\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD \`cardIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD \`cardIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD \`is_archive\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD \`listIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`lists\` ADD \`is_archive\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`lists\` ADD \`boardIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD \`assigned\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD \`is_archive\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD \`projectIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD \`boardMembersId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`assigned\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`is_archive\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`project_members\` ADD \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`project_members\` ADD \`projectIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`userIDId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`accessToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`accessTokenExpiresAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`resetToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`resetTokenExpiresAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`boardMembersId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`cardMembersId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`coverUrl\` \`coverUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`priority\` \`priority\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`startDate\` \`startDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`dueDate\` \`dueDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`coverUrl\` \`coverUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`data\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`data\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatarUrl\` \`avatarUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD CONSTRAINT \`FK_e635eb7677b92b43c746afb0c33\` FOREIGN KEY (\`cardIDId\`) REFERENCES \`cards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD CONSTRAINT \`FK_060d5839fbc02bdca25f57a2206\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_5fd7e1818269b78c2740fc27771\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_b202e040bcab8687fa432628fba\` FOREIGN KEY (\`cardIDId\`) REFERENCES \`cards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD CONSTRAINT \`FK_2cc808bbdb6f4e1169a8916d0a6\` FOREIGN KEY (\`listIDId\`) REFERENCES \`lists\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`lists\` ADD CONSTRAINT \`FK_35ce69b6248c3fdac997094de16\` FOREIGN KEY (\`boardIDId\`) REFERENCES \`boards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD CONSTRAINT \`FK_a18ef38e5a44e510d18d2845e8d\` FOREIGN KEY (\`projectIDId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD CONSTRAINT \`FK_aa2621c1c7f36b4bb38945f8d8c\` FOREIGN KEY (\`boardMembersId\`) REFERENCES \`board_members\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_members\` ADD CONSTRAINT \`FK_24cae15cf042f411ce2ccae3c1f\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`project_members\` ADD CONSTRAINT \`FK_d8433ad1d7964e95ddad79d2cfe\` FOREIGN KEY (\`projectIDId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_554429ae7394b1fd4f26f45a623\` FOREIGN KEY (\`userIDId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_f1ea56a230dc4111559f74f64c5\` FOREIGN KEY (\`boardMembersId\`) REFERENCES \`board_members\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_ae2afa612c84f4eb307d6c652be\` FOREIGN KEY (\`cardMembersId\`) REFERENCES \`card_members\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_ae2afa612c84f4eb307d6c652be\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_f1ea56a230dc4111559f74f64c5\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_554429ae7394b1fd4f26f45a623\``);
        await queryRunner.query(`ALTER TABLE \`project_members\` DROP FOREIGN KEY \`FK_d8433ad1d7964e95ddad79d2cfe\``);
        await queryRunner.query(`ALTER TABLE \`project_members\` DROP FOREIGN KEY \`FK_24cae15cf042f411ce2ccae3c1f\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP FOREIGN KEY \`FK_aa2621c1c7f36b4bb38945f8d8c\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP FOREIGN KEY \`FK_a18ef38e5a44e510d18d2845e8d\``);
        await queryRunner.query(`ALTER TABLE \`lists\` DROP FOREIGN KEY \`FK_35ce69b6248c3fdac997094de16\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP FOREIGN KEY \`FK_2cc808bbdb6f4e1169a8916d0a6\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_b202e040bcab8687fa432628fba\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP FOREIGN KEY \`FK_5fd7e1818269b78c2740fc27771\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP FOREIGN KEY \`FK_060d5839fbc02bdca25f57a2206\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP FOREIGN KEY \`FK_e635eb7677b92b43c746afb0c33\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`avatarUrl\` \`avatarUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`data\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`data\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`coverUrl\` \`coverUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`boards\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`dueDate\` \`dueDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`startDate\` \`startDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`priority\` \`priority\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` CHANGE \`coverUrl\` \`coverUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`cardMembersId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`boardMembersId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`resetTokenExpiresAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`resetToken\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`accessTokenExpiresAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`accessToken\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`userIDId\``);
        await queryRunner.query(`ALTER TABLE \`project_members\` DROP COLUMN \`projectIDId\``);
        await queryRunner.query(`ALTER TABLE \`project_members\` DROP COLUMN \`userIDId\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`is_archive\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`assigned\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP COLUMN \`boardMembersId\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP COLUMN \`projectIDId\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP COLUMN \`is_archive\``);
        await queryRunner.query(`ALTER TABLE \`boards\` DROP COLUMN \`assigned\``);
        await queryRunner.query(`ALTER TABLE \`lists\` DROP COLUMN \`boardIDId\``);
        await queryRunner.query(`ALTER TABLE \`lists\` DROP COLUMN \`is_archive\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP COLUMN \`listIDId\``);
        await queryRunner.query(`ALTER TABLE \`cards\` DROP COLUMN \`is_archive\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP COLUMN \`cardIDId\``);
        await queryRunner.query(`ALTER TABLE \`comments\` DROP COLUMN \`userIDId\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP COLUMN \`userIDId\``);
        await queryRunner.query(`ALTER TABLE \`card_members\` DROP COLUMN \`cardIDId\``);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD \`projectsId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`lists\` ADD \`boardsId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD \`listId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD \`cardMembersId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD \`cardsId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD \`usersId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD \`projectsId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`DROP TABLE \`board_members\``);
        await queryRunner.query(`ALTER TABLE \`boards\` ADD CONSTRAINT \`FK_8b9db493288097ceee34689fc34\` FOREIGN KEY (\`projectsId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`lists\` ADD CONSTRAINT \`FK_6077f5aded72378587df070fbfd\` FOREIGN KEY (\`boardsId\`) REFERENCES \`boards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD CONSTRAINT \`FK_8e71fba12a609e08cf311fde6d9\` FOREIGN KEY (\`listId\`) REFERENCES \`lists\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cards\` ADD CONSTRAINT \`FK_19ac373d1ef1e68e87e5a3633db\` FOREIGN KEY (\`cardMembersId\`) REFERENCES \`card_members\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_5c7e0f84a46dc141ed67180cef2\` FOREIGN KEY (\`cardsId\`) REFERENCES \`cards\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`comments\` ADD CONSTRAINT \`FK_065338fbfc15984038082f46bd1\` FOREIGN KEY (\`usersId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`card_members\` ADD CONSTRAINT \`FK_765ababa7eff37efc56ec24ac9f\` FOREIGN KEY (\`projectsId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
